[package]
name = "trait_host"
version = "0.1.0"
edition = "2018"
authors = ["Martin Molzer <ga65guy@mytum.de>"]

[lib]
name = "trait_host"
path = "src/lib.rs"

[dependencies]
ref-cast = { version = "1.0.6", optional = true }

[features]
with-alternative = ["ref-cast"]
